export const CLASSES = {
  Archer:    { icon: '🏹', label: 'Archer',          color: '#22c55e' },
  Swordsman: { icon: '⚔️', label: 'Swordsman',       color: '#f97316' },
  Mage:      { icon: '🔮', label: 'Mage',            color: '#a78bfa' },
  Martial:   { icon: '🥊', label: 'Martial Artist',  color: '#60a5fa' },
}

export const RARITY_COLORS = {
  Legendary: '#c9a84c',
  Epic:      '#a78bfa',
  Rare:      '#60a5fa',
  Common:    '#86efac',
}

// ── Shared character constants ─────────────────────────────────────────────

export const STAT_KEYS    = ['atk', 'def', 'matk', 'mdef', 'hp', 'mp', 'speed', 'critRate', 'critDmg', 'hit', 'avoid']
export const EQUIP_KEYS   = ['weapon', 'offhand', 'armor', 'hat', 'gloves', 'shoes', 'necklace', 'ring', 'bracelet', 'costumeWings', 'costumeTop', 'costumeBottom']
export const SPECIAL_KEYS = ['fairy']
export const ELEMENTS     = ['Neutral', 'Fire', 'Water', 'Light', 'Shadow']

// ── Specialist cards (SP) by class ────────────────────────────────────────
const I = (id) => `https://nosapki.com/images/icons/${id}.png`

export const SPECIALISTS = {
  Archer: [
    { name: 'Ranger',               icon: I(903)  },
    { name: 'Assassin',             icon: I(904)  },
    { name: 'Destructeur',          icon: I(911)  },
    { name: 'Garde-chasse',         icon: I(912)  },
    { name: 'Canonnier de feu',     icon: I(2545) },
    { name: 'Éclaireur',            icon: I(2589) },
    { name: 'Chasseur de démons',   icon: I(2655) },
    { name: 'Ange vengeur',         icon: I(2707) },
    { name: 'Traqueur solaire',     icon: I(4494) },
    { name: 'Grenadier',            icon: I(4860) },
    { name: 'Chasseur nébuleux',    icon: I(7139) },
  ],
  Swordsman: [
    { name: 'Guerrier',             icon: I(901)  },
    { name: 'Ninja',                icon: I(902)  },
    { name: 'Croisé',               icon: I(909)  },
    { name: 'Berserk',              icon: I(910)  },
    { name: 'Gladiateur',           icon: I(2544) },
    { name: 'Moine pugnace',        icon: I(2588) },
    { name: 'Mortifère',            icon: I(2654) },
    { name: 'Renégat',              icon: I(2706) },
    { name: 'Hacheur',              icon: I(4496) },
    { name: 'Chevalier dragon',     icon: I(4862) },
    { name: 'Broyeur de pierre',    icon: I(7138) },
  ],
  Mage: [
    { name: 'Mage du feu',          icon: I(905)  },
    { name: 'Mage sacré',           icon: I(906)  },
    { name: 'Mage de glace',        icon: I(913)  },
    { name: 'Mage ténébreux',       icon: I(914)  },
    { name: 'Volcanor',             icon: I(2546) },
    { name: 'Sa Majesté des marées',icon: I(2590) },
    { name: 'Devin',                icon: I(2656) },
    { name: 'Archimage',            icon: I(2708) },
    { name: 'Prêtre vaudou',        icon: I(4497) },
    { name: 'Gravitas',             icon: I(4863) },
    { name: 'Tempête de feu',       icon: I(7140) },
  ],
  Martial: [
    { name: 'Arts mystiques',       icon: I(4093) },
    { name: 'Maître loup',          icon: I(4126) },
    { name: 'Guerrier-démon',       icon: I(4151) },
    { name: 'Druide ardent',        icon: I(4495) },
    { name: 'Hydraupoing',          icon: I(4861) },
    { name: 'Foudroyeur',           icon: I(7141) },
  ],
}

// ── Weapon rarities ───────────────────────────────────────────────────────
// rank: display label for the rank tier | label: rarity name (empty = no name at R0)
export const WEAPON_RARITIES = [
  { key: 'r-2', rank: 'R-2', label: 'Endommagée',        color: '#FF9085' },
  { key: 'r-1', rank: 'R-1', label: 'Bas-Niveau',        color: '#FFA8CC' },
  { key: 'r0',  rank: 'R0',  label: '',                  color: '#F2F2F2' },
  { key: 'r1',  rank: 'R1',  label: 'Utile',             color: '#C0BDFC' },
  { key: 'r2',  rank: 'R2',  label: 'Bon',               color: '#72FF85' },
  { key: 'r3',  rank: 'R3',  label: 'De grande qualité', color: '#91CDFF' },
  { key: 'r4',  rank: 'R4',  label: 'Excellent',         color: '#0EF902' },
  { key: 'r5',  rank: 'R5',  label: 'Antique',           color: '#F8E2B3' },
  { key: 'r6',  rank: 'R6',  label: 'Mystérieux',        color: '#F2DD02' },
  { key: 'r7',  rank: 'R7',  label: 'Légendaire',        color: '#B2F304' },
  { key: 'r8',  rank: 'R8',  label: 'Phénoménal',        color: '#FF5E00' },
]

// ── Runic skills (compétences runiques) ───────────────────────────────────
export const RUNIC_COLOR = '#cd6f29'
export const RUNIC_EFFECTS = [
  { key: 'runicAtkFlat',    label: 'Toutes les attaques augmentent de' },
  { key: 'runicDmgMonster', label: 'Les dégâts contre les monstres augmentent de %' },
  { key: 'runicCritRate',   label: 'La probabilité de provoquer un coup critique augmente de %' },
  { key: 'runicCritDmg',    label: 'Les dégâts infligés par coups critiques augmentent de %' },
  { key: 'runicDmgDragon',  label: 'Les dégâts contre les dragons de haut niveau augmentent de %' },
  { key: 'runicFairyElem',  label: "L'élément de la fée équipée augmente de" },
  { key: 'runicSpAtk',      label: "Les points de compétence d'attaque de ton spécialiste augmentent de" },
  { key: 'runicSpElem',     label: "Les points de compétence de l'élément de ton spécialiste augmentent de" },
  { key: 'runicAtkPct',     label: 'Toutes les attaques augmentent de %' },
]

// ── Shell (coquillage) rune system ────────────────────────────────────────
export const SHELL_RANK_COLORS = {
  C: '#e6bb13',
  B: '#e8e83c',
  A: '#a5fe5e',
  S: '#c7f998',
}

export const SHELL_EFFECTS = [
  { key: 'atkBoost',    label: 'Attaque augmentée',                                              ranges: { C:[22,95],  B:[44,142],  A:[87,190] } },
  { key: 'dmgIncrease', label: 'Les dégâts augmentent',                                          ranges: { S:[5,19] } },
  { key: 'dmgPlants',   label: 'Dégâts augmentés sur les plantes',                               ranges: { C:[1,9],   B:[5,19],    A:[9,19] } },
  { key: 'dmgAnimals',  label: 'Dégâts augmentés sur les animaux',                               ranges: { C:[1,9],   B:[5,19],    A:[9,19] } },
  { key: 'dmgMonsters', label: 'Dégâts augmentés sur les monstres',                              ranges: { C:[1,9],   B:[5,19],    A:[9,19] } },
  { key: 'dmgUndead',   label: 'Les dégâts contre les morts-vivants augmentent',                 ranges: { C:[1,9],   B:[5,19],    A:[9,19] } },
  { key: 'dmgKovolts',  label: 'Les dégâts contre les kovolts, catsys et ratufus augmentent',   ranges: { C:[1,9],   B:[5,19],    A:[9,19] } },
  { key: 'dmgMapBoss',  label: 'Les dégâts sur les boss de carte augmentent',                    ranges: { S:[13,23] } },
  { key: 'critDmg',     label: 'Augmente les dégâts critiques',                                  ranges: { C:[12,57] } },
  { key: 'elemFire',    label: 'Élément Feu renforcé',                                           ranges: { B:[10,76], A:[27,142] } },
  { key: 'elemWater',   label: 'Élément Eau renforcé',                                           ranges: { B:[10,76], A:[27,142] } },
  { key: 'elemLight',   label: 'Élément Lumière renforcé',                                       ranges: { B:[10,76], A:[27,142] } },
  { key: 'elemDark',    label: "L'élément Obscurité augmente",                                   ranges: { B:[10,76], A:[27,142] } },
  { key: 'elemAll',     label: 'Tous les éléments sont renforcés',                               ranges: { S:[95,171] } },
  { key: 'spAtk',       label: "Les statistiques d'attaque (SP) augmentent",                     ranges: { B:[3,11],  A:[4,17] } },
  { key: 'spDef',       label: 'Augmente la défense de la SP de',                                ranges: { B:[3,11],  A:[4,17] } },
  { key: 'spElem',      label: 'Les points de compétence élémentaires (SP) augmentent',          ranges: { B:[3,11],  A:[4,17] } },
  { key: 'spHpmp',      label: 'Augmente les HP/MP de la SP de',                                 ranges: { B:[3,11],  A:[4,17] } },
  { key: 'spAll',       label: 'Augmentation générale des points de la SP de',                   ranges: { S:[5,11] } },
]

// ── Weapons by class ─────────────────────────────────────────────────────
// minLevel: required character level (null for heroic)
// minHero:  required hero level (null for regular)
const W  = (name, id, minLevel) => ({ name, icon: I(id), minLevel, minHero: null })
const WH = (name, id, minHero)  => ({ name, icon: I(id), minLevel: null, minHero })

export const WEAPONS = {
  Swordsman: [
    W('Bâton de bois',                                   1,    1),
    W('Gourdin en bois',                                 2,    4),
    W('Épée en bois',                                    3,    7),
    W('Marteau en bois',                                 4,   10),
    W('Marteau en bois lourd',                           5,   13),
    W("Épée en bois d'apprenti",                         6,   15),
    W("Épée d'Aventurier",                               7,   18),
    W("Épée d'apprenti",                                18,   15),
    W('Épée courte',                                    19,   20),
    W('Glaive',                                        135,   21),
    W('Épée de peine',                                  20,   26),
    W('Épée courte',                                    21,   29),
    W('Épée wallonne',                                 136,   30),
    W('Épée en bronze',                                 22,   34),
    W('Sabre',                                          23,   36),
    W('Sabre viking',                                  137,   37),
    W("Épée large de l'esprit",                         24,   40),
    W('Fauchon',                                        25,   42),
    W('Machette',                                      138,   43),
    W("Épée d'Elvin",                                  262,   45),
    W('Sabre en or',                                    26,   46),
    W('Épée large',                                     27,   48),
    W('Katzbalger',                                    139,   49),
    W('Épée longue du pouvoir',                         28,   52),
    W('Épée large',                                     29,   53),
    W('Épée de chevalier',                             140,   54),
    W('Skyabona',                                       30,   57),
    W('Épée claymore',                                  31,   60),
    W('Épée assassine',                                141,   63),
    W('Sabre glorieux',                                263,   65),
    W('Sabre vif',                                     263,   68),
    W('Surin',                                         299,   70),
    W('Loopuster',                                     400,   71),
    W('Lame laminante',                                299,   73),
    W('Épée élémentaire brisée',                       264,   75),
    W('Épée brisée',                                   401,   79),
    W('Épée tranchante du grand chef',                4001,   81),
    W('Épée du héros oublié +10',                     2465,   81),
    W('Honorable : épée houleuse de Calvina',          262,   82),
    W('Épée longue des voleurs du désert',             349,   83),
    W('Épée incendiaire de Magmaros',                 2464,   83),
    W('Lame épineuse',                                 349,   85),
    W('Épée incendiaire de Valakus',                  2406,   85),
    W("Lance obscure d'Hatus",                         350,   88),
    W('Schiavona',                                     350,   88),
    W('Épée houleuse de Calvina',                      350,   88),
    W('Honorable : épée tranchante du grand chef',     349,   88),
    WH('Épée de chef de guerre orc',                  4160,   10),
    WH('Épée céleste scellée',                        2759,   25),
    WH('Épée infernale scellée',                      2767,   25),
    WH('La lame droite de Krem brisé',                2813,   45),
    WH('Épée au loa lion',                            4161,   55),
    WH('Épée magique de Bélial',                      4162,   60),
    WH('Épée en os de dragon',                        4628,   65),
    WH('Pourfendeur de dragons',                      4629,   80),
    WH('Épée sacrée',                                 4944,   83),
    WH("Épée instable d'Achille",                     7599,   83),
    WH('Épée rotative',                               4945,   90),
    WH("Épée d'Achille",                              7503,   93),
    WH('Épée styxienne du fils de Thétis',            7504,   99),
  ],
  Archer: [
    W("Arc d'apprenti",                               32,   15),
    W('Petit arc',                                    33,   20),
    W('Arc de la vie',                               142,   21),
    W('Arc de vitesse',                               34,   26),
    W('Arc en bambou',                                35,   29),
    W('Arc de flammes',                              143,   30),
    W('Arc magique',                                  36,   34),
    W('Arc en chêne',                                 37,   36),
    W('Arc synthétique',                             144,   37),
    W('Arc du vent',                                  38,   40),
    W('Arc à corne',                                  39,   42),
    W('Arc double',                                  145,   43),
    W('Arc rouge',                                   265,   45),
    W('Arc en cuir',                                  40,   46),
    W('Arc de chasse',                                41,   48),
    W('Arc féroce',                                  146,   49),
    W('Arc du courage',                               42,   52),
    W('Arc long',                                     43,   53),
    W('Grand arc',                                   147,   54),
    W('Arc en bronze',                                44,   57),
    W("Arc de l'esprit",                              45,   60),
    W('Arc de siège',                                148,   63),
    W('Arc de la paix',                              266,   65),
    W('Arc de la forêt',                             266,   68),
    W('Arc de pouvoir',                              300,   70),
    W('Séraphin',                                    403,   71),
    W("Arc d'ange noir",                             300,   73),
    W('Arc majestueux',                              267,   75),
    W('Caipéru',                                     404,   79),
    W('Arc du grand chef',                          4003,   81),
    W('Arc du héros oublié +10',                    2467,   81),
    W('Honorable : arc tsunamique de Calvina',       265,   82),
    W('Arc des voleurs du désert',                   353,   83),
    W('Aile du phénix',                             2466,   83),
    W('Arc élémentaire',                             353,   85),
    W('Aile de Graal',                              2407,   85),
    W('Arc de la destruction',                       354,   88),
    W("Arc du précipice d'Hatus",                    354,   88),
    W('Arc tsunamique de Calvina',                   354,   88),
    W('Honorable : arc du grand chef',               353,   88),
    WH('Arc du maître-archer orc',                  4163,   10),
    WH('Arc céleste scellé',                        2761,   25),
    WH('Arc infernal scellé',                       2769,   25),
    WH("Ailes d'Azraël",                            2816,   45),
    WH('Arc au loa aigle',                          4164,   55),
    WH('Arc maudit de Bélial',                      4165,   60),
    WH('Arc draconique',                            4632,   65),
    WH('Souffle de la destruction',                 4633,   80),
    WH("Arc d'engrenage",                           4947,   83),
    WH("Arc instable de l'amiral Yi",               7600,   83),
    WH('Arc à vapeur',                              4946,   90),
    WH("Arc de l'amiral Yi",                        7505,   93),
    WH('Arc des guerres navales de Joseon',         7506,   99),
  ],
  Mage: [
    W("Baguette magique d'apprenti",                 46,   15),
    W('Baguette magique à perle rouge',              47,   20),
    W('Baguette magique de la vie',                 149,   21),
    W("Baguette magique de l'esprit",                48,   26),
    W('Baguette magique à rubis',                    49,   29),
    W('Baguette magique de flamme',                 150,   30),
    W('Baguette magique enchantée',                  50,   34),
    W('Baguette magique à perle bleue',              51,   36),
    W('Baguette magique de glace',                  151,   37),
    W('Baguette magique de la Lumière',              52,   40),
    W('Baguette magique à opale',                    53,   42),
    W('Baguette magique de Loon',                   152,   43),
    W('Baguette magique légendaire',                268,   45),
    W('Baguette magique créatrice de mana',          54,   46),
    W('Baguette magique à corail',                   55,   48),
    W('Baguette magique',                           153,   49),
    W("Baguette magique de l'honneur",               56,   52),
    W('Baguette magique à cristal',                  57,   53),
    W('Baguette magique sacrée',                    154,   54),
    W("Baguette magique de l'intelligence",          58,   57),
    W("Baguette magique de l'Obscurité",             59,   60),
    W("Baguette magique de l'âme",                 155,   63),
    W('Baguette magique du fantôme',                269,   65),
    W('Baguette magique à crâne',                   269,   68),
    W('Baguette magique de Kai',                    301,   70),
    W('Baguette magique du seigneur Mukraju',        406,   71),
    W("Baguette magique de l'Archimage",             301,   73),
    W('Baguette magique majestueuse',               270,   75),
    W("Baguette d'Aurélius",                        407,   79),
    W('Baguette magique du grand chef',            4005,   81),
    W('Baguette magique du héros oublié +10',      2469,   81),
    W('Honorable : baguette magique hydrophyte de Calvina', 268, 82),
    W('Canne des voleurs du désert',                356,   83),
    W('Bâton du spectre de lave',                  2468,   83),
    W('Baguette magique séraphin',                  356,   85),
    W('Baguette magique de Yertirand',             2938,   85),
    W('Baguette magique de Yertirand corrompu',    2939,   85),
    W('Baguette de Katol',                         2408,   85),
    W('Baguette magique de Taracen',                357,   88),
    W("Baguette infernale de Hatus",                357,   88),
    W('Baguette magique hydrophyte de Calvina',     357,   88),
    W('Honorable : baguette magique du grand chef', 356,   88),
    WH('Bâton divin du maître sorcier',            4166,   10),
    WH('Bâton céleste scellé',                     2760,   25),
    WH('Bâton infernal scellé',                    2768,   25),
    WH('Branche de lumière de Seli-Lusha',         2817,   45),
    WH('Bâton au loa serpent',                     4167,   55),
    WH('Bâton du roi des esprits',                 4168,   60),
    WH('Baguette magique draconique',              4630,   65),
    WH('Baguette animique draconique',             4631,   80),
    WH('Baguette magique électrique',              4948,   83),
    WH('Baguette instable de Merlin',              7601,   83),
    WH("Baguette magique d'énergie",               4949,   90),
    WH('Baguette de Merlin',                       7507,   93),
    WH("Baguette d'Avalon",                        7508,   99),
  ],
  Martial: [
    W("Poing d'acier",                             4014,   80),
    W('Gant de cavalier court',                    4012,   80),
    W('Gant en acier froid',                       4019,   81),
    W('Larme de Ladine',                           4020,   81),
    W('Gant des arts martiaux',                    4013,   82),
    W('Main noire',                                4016,   82),
    W('Griffe de Fenris',                          4021,   83),
    W('Gant de golem de feu',                      4022,   83),
    W('Gant en cuir renforcé',                     4012,   84),
    W('Gant des arts martiaux en cuir',            4013,   84),
    W("Gant d'écailles du chaos",                  4023,   85),
    W("Flamme de l'Ifrit",                         4024,   85),
    W('Gant puissant',                             4015,   86),
    W("Gant de l'apprenti assassin",               4017,   86),
    W('Gant de Sicario',                           4017,   88),
    W('Poing noir',                                4018,   88),
    WH('Gants de plaques orcs en sekrass',         4169,   10),
    WH('Poing de la déesse scellée',               4025,   25),
    WH('Poing de dieu',                            4026,   45),
    WH('Gants de plaques au loa ours',             4170,   55),
    WH('Gants de plaques du roi des bêtes',        4171,   60),
    WH('Griffe draconique',                        4626,   65),
    WH('Griffe givrée',                            4627,   80),
    WH('Gantelets à vapeur',                       4950,   83),
    WH('Gants instables de Thor',                  7602,   83),
    WH("Gantelets d'allumage",                     4951,   90),
    WH('Gants de Thor',                            7509,   93),
    WH('Gants du tonnerre de Niflheim',            7510,   99),
  ],
}

// ── Secondary weapons (armes secondaires) by class ────────────────────────
export const SECONDARY_WEAPONS = {
  Swordsman: [
    W("Catapulte en bois",                                     8,    1),
    W("Catapulte en bois puissante",                           9,    6),
    W("Catapulte en bois d'apprenti",                          10,   12),
    W("Catapulte d'Aventurier",                                11,   16),
    W("Arbalète d'apprenti",                                   68,   15),
    W("Arbalète en chêne",                                     69,   20),
    W("Arbalète de combat",                                    156,  21),
    W("Arbalète féérique",                                     70,   27),
    W("Arbalète d'acier",                                      73,   33),
    W("Arbalète magistrale",                                   74,   41),
    W("Arbalète Winslet",                                      291,  44),
    W("Arbalète de l'Obscurité",                               75,   47),
    W("Arbalète de siège",                                     157,  48),
    W("Arbalète en hêtre",                                     76,   53),
    W("Arbalète du courage",                                   77,   56),
    W("Arbalète elfique",                                      77,   64),
    W("Arbalète Balenty",                                      292,  67),
    W("Baliste",                                               292,  72),
    W("Bergarce",                                              402,  74),
    W("Arbalète du vagabond du désert",                        291,  80),
    W("Arbalète du grand chef",                                352,  81),
    W("Arbalète du héros oublié +10",                          2411, 81),
    W("Honorable : arbalète d'épine bleue de Calvina",         292,  82),
    W("Griffe du phénix",                                      2409, 83),
    W("Arbalète de héros",                                     352,  85),
    W("Griffe de Graal",                                       2410, 85),
    W("Arbalète d'épine bleue de Calvina",                     292,  88),
    W("Honorable : arbalète du grand chef",                    402,  88),
    WH("Arbalète de chef de guerre orc",                       4172, 10),
    WH("Arbalète céleste scellée",                             2762, 25),
    WH("Arbalète infernale scellée",                           2780, 25),
    WH("Arbalète brillante de Luminiel",                       2815, 45),
    WH("Arbalète au loa lion",                                 4173, 55),
    WH("Arbalète du roi des bêtes",                            4174, 60),
    WH("Arbalète draconienne",                                 4634, 65),
    WH("Arbalète de cristal draconique",                       4635, 80),
    WH("Arbalète d'engrenage",                                 4936, 82),
    WH("Fusil arbalète",                                       4937, 88),
    WH("Arbalète d'Achille",                                   7511, 92),
    WH("Arbalète styxienne du fils de Thétis",                 7512, 98),
  ],
  Archer: [
    W("Dague d'apprenti",                                      78,   15),
    W("Dague",                                                 79,   20),
    W("Dague de montagnard",                                   158,  21),
    W("Dague de torture",                                      80,   27),
    W("Dague noble",                                           81,   33),
    W("Dague magistrale",                                      82,   41),
    W("Tranchoir",                                             289,  44),
    W("Dague en laiton",                                       83,   47),
    W("Dague poignard",                                        159,  48),
    W("Dague à rubis",                                         84,   53),
    W("Dague de l'esprit",                                     85,   58),
    W("Dague elfique",                                         85,   64),
    W("Kriss",                                                 290,  67),
    W("Kriss de l'Obscurité",                                  290,  72),
    W("Écaracci",                                              405,  74),
    W("Dague du scorpion du désert",                           289,  80),
    W("Couteau du grand chef",                                 351,  81),
    W("Dague du héros oublié +10",                             2414, 81),
    W("Honorable : dague de canine bleue de Calvina",          290,  82),
    W("Canine du chien de braise",                             2412, 83),
    W("Tranchoir héroïque",                                    351,  85),
    W("Canine de Kertos",                                      2413, 85),
    W("Dague de canine bleue de Calvina",                      290,  88),
    W("Honorable : couteau du grand chef",                     405,  88),
    WH("Dague d'assassin orc",                                 4175, 10),
    WH("Dague céleste sacrée",                                 2764, 25),
    WH("Dague infernale scellée",                              2766, 25),
    WH("La lame gauche de Krem brisé",                         2814, 45),
    WH("Dague au loa chauve-souris",                           4176, 55),
    WH("Couteau de Bélial",                                    4177, 60),
    WH("Dague draconienne",                                    4636, 65),
    WH("Dague d'os de dragon",                                 4637, 80),
    WH("Dague d'engrenage",                                    4938, 82),
    WH("Dague à vapeur à cartouche",                           4939, 88),
    WH("Épée longue de l'amiral Yi",                           7513, 92),
    WH("Épée des guerres navales de Joseon",                   7514, 98),
  ],
  Mage: [
    W("Arme enchantée d'apprenti",                             86,   15),
    W("Petite arme enchantée",                                 87,   20),
    W("Arme enchantée normale",                                160,  21),
    W("Arme enchantée magique",                                88,   27),
    W("Arme enchantée dorée",                                  89,   33),
    W("Arme enchantée chef-d'œuvre",                           90,   41),
    W("Arme enchantée paff",                                   293,  44),
    W("Arme enchantée en laiton",                              91,   47),
    W("Arme enchantée en bronze",                              161,  48),
    W("Noble arme enchantée",                                  92,   53),
    W("Arme enchantée de l'Obscurité",                         93,   58),
    W("Arme enchantée fantomatique",                           93,   64),
    W("Arme enchantée de la Lumière",                          294,  67),
    W("Arme enchantée étoilée",                                294,  72),
    W("Rénobir",                                               408,  74),
    W("Arme enchantée des mages du désert",                    293,  80),
    W("Arme enchantée du grand chef",                          355,  81),
    W("Arme enchantée du héros oublié +10",                    2417, 81),
    W("Honorable : arme magique de corne bleue de Calvina",    294,  82),
    W("Souffle de Valaket",                                    2415, 83),
    W("Arme enchantée héroïque",                               355,  85),
    W("Souffle de Valakus",                                    2416, 85),
    W("Arme enchantée de la corne bleue de Calvina",           294,  88),
    W("Honorable : arme enchantée du grand chef",              408,  88),
    WH("Arme enchantée orc",                                   4178, 10),
    WH("Arme enchantée céleste scellée",                       2763, 25),
    WH("Arme enchantée infernale scellée",                     2765, 25),
    WH("Arme enchantée du Lorten souterrain",                  2818, 45),
    WH("Arme enchantée au loa serpent",                        4179, 55),
    WH("Flamme éternelle du roi des esprits",                  4180, 60),
    WH("Arme enchantée draconienne",                           4638, 65),
    WH("Arme enchantée du givre",                              4639, 80),
    WH("Pistolet d'engrenage",                                 4940, 82),
    WH("Pistolet à énergie",                                   4941, 88),
    WH("Arme enchantée de Merlin",                             7515, 92),
    WH("Arme enchantée frémissante d'Avalon",                  7516, 98),
  ],
  Martial: [
    W("Insigne de bronze avec un cheval",                      4061, 80),
    W("Insigne de bronze avec deux chevaux",                   4062, 81),
    W("Insigne d'or avec un cheval",                           4067, 81),
    W("Insigne de bronze avec trois chevaux",                  4063, 83),
    W("Insigne d'or avec deux chevaux",                        4068, 83),
    W("Insigne d'argent avec un cheval",                       4064, 85),
    W("Insigne d'or avec trois chevaux",                       4069, 85),
    W("Insigne d'argent avec deux chevaux",                    4065, 87),
    W("Insigne d'argent avec trois chevaux",                   4066, 89),
    WH("Marque de jade en sekrass",                            4181, 10),
    WH("Insigne du dragon bleu magique",                       4070, 25),
    WH("Insigne du tigre blanc magique",                       4071, 25),
    WH("Insigne du phœnix rouge magique",                      4072, 25),
    WH("Insigne de la tortue noire magique",                   4073, 25),
    WH("Marque de jade en sekrass bénie",                      4182, 55),
    WH("Marque au loa ours",                                   4183, 60),
    WH("Jade draconique",                                      4640, 65),
    WH("Œil draconique",                                       4641, 80),
    WH("Bouclier argenté d'engrenage",                         4942, 82),
    WH("Bouclier doré d'engrenage",                            4943, 88),
    WH("Bouclier couvert de runes",                            7517, 92),
    WH("Bouclier runique de Thor",                             7518, 98),
  ],
}

// ── Armors by class ───────────────────────────────────────────────────────
export const ARMORS = {
  Swordsman: [
    W("Vêtement",                                              12,   1),
    W("Tenue d'entraînement",                                  13,   3),
    W("Tenue d'Aventurier",                                    14,   8),
    W("Armure d'entraînement",                                 15,   11),
    W("Lot du manteau du voyageur",                            16,   14),
    W("Lot de manteau chaud",                                  17,   17),
    W("Armure d'apprenti Épéiste",                             94,   15),
    W("Armure rembourrée",                                     95,   19),
    W("Armure de sécurité",                                    162,  20),
    W("Armure molletonnée",                                    96,   24),
    W("Armure en cuir",                                        97,   27),
    W("Armure en cuir robuste",                                163,  28),
    W("Armure d'endurance",                                    98,   32),
    W("Armure en cuir à boulons",                              99,   34),
    W("Armure de vainqueur",                                   164,  35),
    W("Armure en cuir améliorée",                              100,  39),
    W("Armure à écailles",                                     101,  41),
    W("Armure du gardien",                                     165,  42),
    W("Armure du moral",                                       102,  46),
    W("Armure de plaques",                                     103,  50),
    W("Armure de chevalier",                                   166,  51),
    W("Armure à rivets dorée",                                 104,  55),
    W("Défenseur brave",                                       297,  55),
    W("Brigandine",                                            105,  57),
    W("Armure en pierre",                                      167,  58),
    W("Armure du courage",                                     106,  62),
    W("Garde du corps",                                        106,  65),
    W("Défenseur splendide",                                   298,  69),
    W("Armure cristalline de Bérios",                          279,  70),
    W("Défenseur lourd",                                       298,  74),
    W("Cailander",                                             409,  78),
    W("Honorable : armure or bande voleurs",                   298,  80),
    W("Armure lourde du commandant",                           360,  81),
    W("Armure du héros oublié +10",                            2420, 81),
    W("Armure blindée du géant flammes",                       2418, 83),
    W("Armure or bande voleurs",                               298,  85),
    W("Armure pectorale acier Katol",                          2419, 85),
    W("Armure or étincelante bande voleurs",                   409,  88),
    W("Honorable : armure lourde commandant",                  360,  88),
    WH("Armure de pierre sekrass",                             4184, 10),
    WH("Armure céleste scellée lourde",                        2774, 28),
    WH("Armure infernale scellée lourde",                      2777, 28),
    WH("L'armure lourde du brave Share",                       2819, 48),
    WH("Armure pierre sekrass loa lion",                       4185, 53),
    WH("Armure d'os guerrier orc",                             4186, 58),
    WH("Armure d'écailles draconiques azur",                   4660, 65),
    WH("Armure de pourfendeur dragons",                        4661, 80),
    WH("Costume de mineur",                                    4953, 81),
    WH("Armure à vapeur",                                      4952, 86),
    WH("Armure d'Achille",                                     7519, 91),
    WH("Armure styxienne fils Thétis",                         7520, 97),
  ],
  Archer: [
    W("Tunique apprenti Archer",                               107,  15),
    W("Tunique cuir agneau",                                   108,  19),
    W("Tunique éclair",                                        168,  20),
    W("Tunique velours",                                       109,  24),
    W("Tunique cuir chèvre",                                   110,  27),
    W("Tunique nature",                                        169,  28),
    W("Tunique d'évasion",                                     111,  32),
    W("Tunique peau veau",                                     112,  34),
    W("Tunique cuir requin",                                   170,  35),
    W("Tunique daim",                                          113,  39),
    W("Tunique cuir vache",                                    114,  41),
    W("Tunique du souffle",                                    171,  42),
    W("Tunique d'œil d'aigle",                                 115,  46),
    W("Tunique pécari",                                        116,  50),
    W("Tunique du vent",                                       172,  51),
    W("Tunique nubuck",                                        117,  55),
    W("Regard du gardien",                                     295,  55),
    W("Tunique toscane",                                       118,  57),
    W("Tunique dryades",                                       173,  58),
    W("Tunique spectrale",                                     119,  62),
    W("Tunique de chasseur",                                   119,  65),
    W("Robe de lumière",                                       296,  69),
    W("Tunique cristalline Bérios",                            280,  70),
    W("Tunique de brise",                                      296,  74),
    W("Suphirudin",                                            410,  78),
    W("Honorable : tunique or bande voleurs",                  296,  80),
    W("Armure cuir commandant",                                359,  81),
    W("Armure cuir héros oublié +10",                          2423, 81),
    W("Armure cuir chien braise",                              2421, 83),
    W("Tunique or bande voleurs",                              296,  85),
    W("Armure pectorale cuir Kertos",                          2422, 85),
    W("Tunique or étincelante bande voleurs",                  410,  88),
    W("Honorable : armure cuir commandant",                    359,  88),
    WH("Armure cuir maître-chasseur orc",                      4187, 10),
    WH("Armure céleste scellée cuir",                          2776, 28),
    WH("Armure infernale scellée cuir",                        2779, 28),
    WH("L'armure cuir âme argentée glace",                     2820, 48),
    WH("Armure cuir loa aigle",                                4188, 53),
    WH("Armure cuir écailles dragon",                          4189, 58),
    WH("Uniforme éclaireur draconien",                         4654, 65),
    WH("Uniforme chasseur dragons",                            4655, 80),
    WH("Armure chasse à vapeur",                               4954, 81),
    WH("Armure de bandit",                                     4955, 86),
    WH("Armure de l'amiral Yi",                                7521, 91),
    WH("Armure guerres navales Joseon",                        7522, 97),
  ],
  Mage: [
    W("Tenue apprenti Sorcier",                                120,  15),
    W("Tenue coton",                                           121,  19),
    W("Robe apprenti",                                         174,  20),
    W("Tenue coton magique",                                   122,  24),
    W("Robe lin",                                              123,  27),
    W("Robe souple",                                           175,  28),
    W("Tenue de récupération",                                 124,  32),
    W("Robe tweed",                                            125,  34),
    W("Tenue de la clarté",                                    176,  35),
    W("Robe lin améliorée",                                    126,  39),
    W("Robe mousseline",                                       127,  41),
    W("Robe à motif",                                          177,  42),
    W("Robe élémentaire",                                      128,  46),
    W("Robe soie",                                             129,  50),
    W("Tunique magique",                                       178,  51),
    W("Robe à carreaux",                                       130,  55),
    W("Tenue bleue du sage",                                   271,  55),
    W("Robe à chevrons",                                       131,  57),
    W("Tunique de la source",                                  179,  58),
    W("Robe ténèbres",                                         132,  62),
    W("Tenue obscure",                                         132,  65),
    W("Robe d'essai",                                          272,  69),
    W("Robe cristalline Bérios",                               281,  70),
    W("Tenue de la sagesse",                                   272,  74),
    W("Ridyarce",                                              411,  78),
    W("Honorable : robe or bande voleurs",                     272,  80),
    W("Apparat du commandant",                                 358,  81),
    W("Tunique héros oublié +10",                              2426, 81),
    W("Tunique phénix flamboyant",                             2424, 83),
    W("Robe or bande voleurs",                                 272,  85),
    W("Tunique Graal flamboyant",                              2425, 85),
    W("Robe or étincelante bande voleurs",                     411,  88),
    W("Honorable : apparat du commandant",                     358,  88),
    WH("Monture combat sorcier orc",                           4190, 10),
    WH("Robe céleste scellée",                                 2775, 28),
    WH("Robe infernale scellée",                               2778, 28),
    WH("La robe mage Mukraju",                                 2821, 48),
    WH("Monture combat loa serpent",                           4191, 53),
    WH("Robe des rois",                                        4192, 58),
    WH("Tunique expert dragons",                               4658, 65),
    WH("Tunique écailles givrées",                             4659, 80),
    WH("Toge chercheur à vapeur",                              4956, 81),
    WH("Armure foi à vapeur",                                  4957, 86),
    WH("Tunique de Merlin",                                    7523, 91),
    WH("Tunique frémissante d'Avalon",                         7524, 97),
  ],
  Martial: [
    W("Uniforme apprenti arts martiaux",                       4029, 80),
    W("Armure cavalier miteuse",                               4031, 81),
    W("Armure voleurs du désert",                              4034, 81),
    W("Armure d'Akamur",                                       4035, 81),
    W("Armure de cavalier",                                    4031, 83),
    W("Costume de Noir",                                       4032, 83),
    W("Armure du voyageur mystérieux",                         4036, 83),
    W("Uniforme de Felice",                                    4037, 83),
    W("Costume de cuir",                                       4031, 85),
    W("Costume cuir renforcé",                                 4032, 85),
    W("Armure Lord Cuarry",                                    4038, 85),
    W("Armure de l'adversaire",                                4039, 85),
    W("Puissante armure",                                      4033, 87),
    W("Armure apprenti assassin",                              4032, 87),
    W("Armure de Sicario",                                     4032, 89),
    W("Armure du poing noir",                                  4033, 89),
    WH("Armure sekrass légère",                                4193, 10),
    WH("Sainteté de Rumial",                                   4040, 28),
    WH("Armure du champion",                                   4041, 48),
    WH("Armure légère loa ours",                               4194, 53),
    WH("Armure fureur de Carlio",                              4195, 58),
    WH("Armure guerrier draconien",                            4656, 65),
    WH("Armure massacreur dragons",                            4657, 80),
    WH("Tenue de sport à vapeur",                              4958, 81),
    WH("Tenue arts martiaux à vapeur",                         4959, 86),
    WH("Armure de Thor",                                       7525, 91),
    WH("Armure foudroyeur Niflheim",                           7526, 97),
  ],
}

export const ELEMENT_COLORS = {
  Neutral: '#9ca3af',
  Fire:    '#ef4444',
  Water:   '#3b82f6',
  Light:   '#fbbf24',
  Shadow:  '#8b5cf6',
}

export const ELEMENT_ICONS = {
  Neutral: '○',
  Fire:    '🔥',
  Water:   '💧',
  Light:   '✨',
  Shadow:  '🌑',
}

// ── Player accounts (username → up to 4 characters) ───────────────────────

export const mockAccounts = [
  {
    username: 'Veqza',
    characters: [
      {
        id: 'a1-c1', name: 'Lyraethis', class: 'Archer', level: 99, heroLevel: 55, prestige: 3, element: 'Fire',
        stats:       { atk: 12450, def: 8920, matk: null,  mdef: 4800,  hp: 42800, mp: 15200, speed: 22, critRate: 48, critDmg: 250, hit: 95, avoid: 18 },
        equipment:   { weapon: 'Scarlet Moon Bow', offhand: null, armor: 'Eternal Winds Outfit', hat: null, gloves: null, shoes: null, necklace: null, ring: 'Ring of the Dawn', bracelet: null, sp: 'Sharpshooter', fairy: 'Tera the Fire +10' },
        resistances: { fire: 12, water: 5, light: 8, shadow: 3 },
      },
      {
        id: 'a1-c2', name: 'Solaris', class: 'Mage', level: 72, heroLevel: 18, prestige: 0, element: 'Light',
        stats:       { atk: null, def: null, matk: 11200, mdef: 5400, hp: 28000, mp: 22000, speed: 19, critRate: 35, critDmg: 180, hit: 88, avoid: 12 },
        equipment:   { weapon: 'Staff of Broken Stars', offhand: null, armor: 'Celestial Satin Robe', hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: 'Elemental Sage', fairy: 'Lola the Ice +3' },
        resistances: { fire: 5, water: 10, light: 25, shadow: 2 },
      },
    ],
  },
  {
    username: 'Darkblade',
    characters: [
      {
        id: 'a2-c1', name: 'Kaelthas', class: 'Swordsman', level: 87, heroLevel: 32, prestige: 1, element: 'Shadow',
        stats:       { atk: 9800, def: 14200, matk: null, mdef: 8600, hp: 58000, mp: 8400, speed: 16, critRate: 22, critDmg: 150, hit: 90, avoid: 8 },
        equipment:   { weapon: 'Twilight Sword', offhand: null, armor: 'Titanite Armor', hat: null, gloves: null, shoes: null, necklace: null, ring: 'Belt of Strength', bracelet: null, sp: 'Paladin of Light', fairy: 'Celle the Thunder +7' },
        resistances: { fire: 3, water: 3, light: 5, shadow: 15 },
      },
      {
        id: 'a2-c2', name: 'Shadowreaper', class: 'Martial', level: 45, heroLevel: 0, prestige: 0, element: 'Neutral',
        stats:       { atk: null, def: null, matk: null, mdef: null, hp: null, mp: null, speed: null, critRate: null, critDmg: null, hit: null, avoid: null },
        equipment:   { weapon: null, offhand: null, armor: null, hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: null, fairy: null },
        resistances: { fire: 0, water: 0, light: 0, shadow: 0 },
      },
    ],
  },
  {
    username: 'Vaelindra',
    characters: [
      {
        id: 'a3-c1', name: 'Vaelindra', class: 'Mage', level: 99, heroLevel: 62, prestige: 2, element: 'Water',
        stats:       { atk: null, def: null, matk: 15200, mdef: 9800, hp: 32000, mp: 28000, speed: 20, critRate: 55, critDmg: 280, hit: 92, avoid: 15 },
        equipment:   { weapon: 'Crystalline Staff', offhand: null, armor: 'Arcane Robe', hat: null, gloves: null, shoes: null, necklace: 'Wisdom Pendant', ring: null, bracelet: null, sp: 'Sorcerer', fairy: null },
        resistances: { fire: 2, water: 35, light: 8, shadow: 5 },
      },
    ],
  },
  {
    username: 'Zephyr_wind',
    characters: [
      {
        id: 'a4-c1', name: 'Zephir', class: 'Martial', level: 98, heroLevel: 48, prestige: 2, element: 'Neutral',
        stats:       { atk: 10200, def: 9400, matk: null, mdef: 7200, hp: 48000, mp: 10000, speed: 28, critRate: 42, critDmg: 200, hit: 97, avoid: 22 },
        equipment:   { weapon: 'Iron Fists +12', offhand: null, armor: 'Dragon Scale Suit', hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: 'Berserker', fairy: 'Isha the Wind +8' },
        resistances: { fire: 8, water: 8, light: 8, shadow: 8 },
      },
      {
        id: 'a4-c2', name: 'Zephira', class: 'Archer', level: 60, heroLevel: 5, prestige: 0, element: 'Neutral',
        stats:       { atk: 5800, def: 3200, matk: null, mdef: 2400, hp: 18000, mp: 8000, speed: 18, critRate: 28, critDmg: 150, hit: 80, avoid: 14 },
        equipment:   { weapon: null, offhand: null, armor: null, hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: null, fairy: null },
        resistances: { fire: 0, water: 0, light: 0, shadow: 0 },
      },
      {
        id: 'a4-c3', name: 'Stormbringer', class: 'Mage', level: 38, heroLevel: 0, prestige: 0, element: 'Neutral',
        stats:       { atk: null, def: null, matk: null, mdef: null, hp: null, mp: null, speed: null, critRate: null, critDmg: null, hit: null, avoid: null },
        equipment:   { weapon: null, offhand: null, armor: null, hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: null, fairy: null },
        resistances: { fire: 0, water: 0, light: 0, shadow: 0 },
      },
    ],
  },
  {
    username: 'Seraphix',
    characters: [
      {
        id: 'a5-c1', name: 'Seraphix', class: 'Archer', level: 98, heroLevel: 51, prestige: 2, element: 'Light',
        stats:       { atk: 13200, def: 7600, matk: null, mdef: 5200, hp: 38000, mp: 14000, speed: 24, critRate: 52, critDmg: 270, hit: 96, avoid: 20 },
        equipment:   { weapon: 'Seraph Longbow', offhand: null, armor: 'Golden Aegis Coat', hat: null, gloves: null, shoes: null, necklace: 'Holy Amulet', ring: null, bracelet: null, sp: 'Holy Sniper', fairy: 'Asha the Light +11' },
        resistances: { fire: 5, water: 5, light: 30, shadow: 1 },
      },
    ],
  },
  {
    username: 'Drakonis',
    characters: [
      {
        id: 'a6-c1', name: 'Drakonis', class: 'Swordsman', level: 95, heroLevel: 40, prestige: 1, element: 'Fire',
        stats:       { atk: 11500, def: 13000, matk: null, mdef: 7800, hp: 55000, mp: 9200, speed: 17, critRate: 30, critDmg: 160, hit: 91, avoid: 10 },
        equipment:   { weapon: 'Dragonsteel Blade', offhand: null, armor: 'Scale Mail', hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: 'Berserker', fairy: 'Celle the Fire +6' },
        resistances: { fire: 20, water: 2, light: 4, shadow: 4 },
      },
      {
        id: 'a6-c2', name: 'Thornwick', class: 'Martial', level: 85, heroLevel: 22, prestige: 0, element: 'Neutral',
        stats:       { atk: 8900, def: 8100, matk: null, mdef: 6000, hp: 42000, mp: 9500, speed: 25, critRate: 38, critDmg: 190, hit: 89, avoid: 19 },
        equipment:   { weapon: 'Thunder Gauntlets', offhand: null, armor: 'Raging Tiger Suit', hat: null, gloves: null, shoes: null, necklace: null, ring: null, bracelet: null, sp: 'Monk', fairy: null },
        resistances: { fire: 5, water: 5, light: 5, shadow: 5 },
      },
    ],
  },
]

// ── Legacy mock data (used by older components) ────────────────────────────

export const mockCharacters = mockAccounts[0].characters

export const mockPlayer = mockCharacters[0]

// ── Hub data ──────────────────────────────────────────────────────────────

export const mockHubStats = {
  players:   '12,489',
  guilds:    '847',
  raidsDone: '34,201',
}

export const mockNews = [
  {
    id:       1,
    tag:      'Update',
    tagColor: '#c9a84c',
    date:     'March 1, 2026',
    title:    'New Raid: Fortress of Shadows',
    excerpt:  'A new legendary 20-player raid is now available. Unlock exclusive rewards.',
  },
  {
    id:       2,
    tag:      'Event',
    tagColor: '#60a5fa',
    date:     'Feb. 28, 2026',
    title:    'Double XP this weekend!',
    excerpt:  'Enjoy a doubled experience bonus all weekend to celebrate the server anniversary.',
  },
  {
    id:       3,
    tag:      'Community',
    tagColor: '#22c55e',
    date:     'Feb. 25, 2026',
    title:    'Monthly ranking updated',
    excerpt:  "February's ranking is now available. Congratulations to the winners!",
  },
]

export const mockTopPlayers = [
  { rank: 1, name: "Kael'thas", class: 'Swordsman', level: 99, heroLevel: 70, server: 'Alzanor' },
  { rank: 2, name: 'Lyraethis', class: 'Archer',    level: 99, heroLevel: 55, server: 'Alzanor' },
  { rank: 3, name: 'Vaelindra', class: 'Mage',      level: 99, heroLevel: 62, server: 'Tyr'     },
  { rank: 4, name: 'Zephir',    class: 'Martial',   level: 98, heroLevel: 48, server: 'Alzanor' },
  { rank: 5, name: 'Seraphix',  class: 'Archer',    level: 98, heroLevel: 51, server: 'Fafnir'  },
]
