// Liste des 44 raids NosTale — noms en fr / en / de (source : nosapki.com)
export const RAIDS = [
  { slug: 'mother-cuby',                   fr: 'Mère Cuby',                          en: 'Mother Cuby',                       de: 'Cuby Mutter' },
  { slug: 'ginseng',                        fr: 'Ginseng',                            en: 'Ginseng',                           de: 'Ginseng' },
  { slug: 'dark-castra',                    fr: 'Castra obscur',                      en: 'Dark Castra',                       de: 'Dark Castra' },
  { slug: 'giant-black-spider',             fr: 'Araignée noire géante',              en: 'Giant Black Spider',                de: 'Schwarze Riesenspinne' },
  { slug: 'massive-slade',                  fr: 'Slade géant',                        en: 'Massive Slade',                     de: 'Riesenslade' },
  { slug: 'chicken-king',                   fr: 'Roi poulet',                         en: 'Chicken King',                      de: 'Huhnkönig' },
  { slug: 'namaju',                         fr: 'Namaju',                             en: 'Namaju',                            de: 'Namaju' },
  { slug: 'giant-grasslin',                 fr: 'Herbin géant',                       en: 'Giant Grasslin',                    de: 'Riesiger Grasslin' },
  { slug: 'huge-snowman-head',              fr: 'Tête de bonhomme de neige géante',   en: 'Huge Snowman Head',                 de: 'Großer Schneemannkopf' },
  { slug: 'ibrahim',                        fr: 'Ibrahim',                            en: 'Ibrahim',                           de: 'Ibrahim' },
  { slug: 'jack-o-lantern',                 fr: "Jack O'Lantern",                     en: "Jack O'Lantern",                    de: "Jack O'Lantern" },
  { slug: 'chicken-queen',                  fr: 'Reine poule',                        en: 'Chicken Queen',                     de: 'Huhnkönigin' },
  { slug: 'captain-pete-openg',             fr: "Capitaine Pete O'Peng",              en: "Captain Pete O'Peng",               de: "Captain Pete O'Peng" },
  { slug: 'kertos',                         fr: 'Kertos, le chien-démon',             en: 'Kertos the Demon Dog',              de: 'Kertos, der Dämonenhund' },
  { slug: 'valakus',                        fr: 'Valakus, roi des flammes',           en: 'Valakus King of Fire',              de: 'Feuerkönig Valakus' },
  { slug: 'grenigas',                       fr: 'Grenigas, le dieu du Feu',           en: 'Fire God Grenigas',                 de: 'Feuergott Grenigas' },
  { slug: 'lord-draco',                     fr: 'Sire Draco',                         en: 'Lord Draco',                        de: 'Lord Draco' },
  { slug: 'glacerus',                       fr: 'Glacerus le Rude',                   en: 'Glacerus the Ice Cold',             de: 'Glacerus, der Eiskalte' },
  { slug: 'foxy',                           fr: 'Foxy',                               en: 'Foxy',                              de: 'Foxy' },
  { slug: 'maru',                           fr: 'Maru',                               en: 'Maru',                              de: 'Maru' },
  { slug: 'witch-laurena',                  fr: 'Sorcière Laurena',                   en: 'Witch Laurena',                     de: 'Hexe Laurena' },
  { slug: 'imp-cheongbi',                   fr: 'Diablotin Cheongbi',                 en: 'Imp Cheongbi',                      de: 'Teufelchen Cheongbi' },
  { slug: 'lola-lopears',                   fr: 'Lola Longoreil',                     en: 'Lola Lopears',                      de: 'Lola Löffel' },
  { slug: 'zenas',                          fr: 'Zénas',                              en: 'Zenas',                             de: 'Zenas' },
  { slug: 'erenia',                         fr: 'Erenia',                             en: 'Erenia',                            de: 'Erenia' },
  { slug: 'incomplete-fernon',              fr: 'Fernon incomplète',                  en: 'Incomplete Fernon',                 de: 'Unvollendete Fernon' },
  { slug: 'greedy-fafnir',                  fr: 'Terrible Fafnir',                    en: 'Greedy Fafnir',                     de: 'Gieriger Fafnir' },
  { slug: 'twisted-yertirand',              fr: 'Yertirand corrompu',                 en: 'Twisted Yertirand',                 de: 'Verdorbener Yertirand' },
  { slug: 'mad-professor-macavity',         fr: 'Dr Miaou fou',                       en: 'Mad Professor Macavity',            de: 'Wahnsinniger Dr. Maunz' },
  { slug: 'mad-march-hare',                 fr: 'Lapin de Pâques fou',                en: 'Mad March Hare',                    de: 'Verrückter Osterhase' },
  { slug: 'twisted-spirit-king-kirollas',   fr: 'Kirollas roi des esprits corrompu',  en: 'Twisted Spirit King Kirollas',      de: 'Verdorbener Geisterkönig Kirollas' },
  { slug: 'twisted-beast-king-carno',       fr: 'Carno roi des bêtes corrompu',       en: 'Twisted Beast King Carno',          de: 'Verdorbener Bestienkönig Carno' },
  { slug: 'demon-god-belial',               fr: 'Dieu-démon Bélial',                  en: 'Demon God Belial',                  de: 'Dämonengott Belial' },
  { slug: 'evil-overlord-paimon',           fr: 'Paimon le seigneur maléfique',       en: 'Evil Overlord Paimon',              de: 'Böser Gebieter Paimon' },
  { slug: 'revenant-paimon',                fr: 'Paimon ressuscité',                  en: 'Revenant Paimon',                   de: 'Auferstandener Paimon' },
  { slug: 'zombie-dragon-valehir',          fr: 'Dragon zombie Valehir',              en: 'Zombie Dragon Valehir',             de: 'Zombiedrache Valehir' },
  { slug: 'ice-dragon-alzanor',             fr: 'Alzanor dragon givré',               en: 'Ice Dragon Alzanor',                de: 'Eisdrache Alzanor' },
  { slug: 'weak-asgobas',                   fr: 'Asgobas faible',                     en: 'Weak Asgobas',                      de: 'Schwacher Asgobas' },
  { slug: 'moss-giant-pollutus',            fr: 'Géant moussu Pollutus',              en: 'Moss Giant Pollutus',               de: 'Moosriese Pollutus' },
  { slug: 'giant-arma',                     fr: 'Arma géant',                         en: 'Giant Arma',                        de: 'Riesen-Arma' },
  { slug: 'ultimate-giant-arma',            fr: 'Arma géant absolu',                  en: 'Ultimate Giant Arma',               de: 'Vollständiger Riesen-Arma' },
  { slug: 'lord-melonoth',                  fr: 'Sire Melonoth',                      en: 'Lord Melonoth',                     de: 'Lord Melonoth' },
  { slug: 'nezarun',                        fr: 'Nézarun',                            en: 'Nezarun',                           de: 'Nezarun' },
  { slug: 'crusher-nezarun',               fr: 'Nézarun dévastateur',                en: 'Crusher Nezarun',                   de: 'Zermalmer Nezarun' },
]
